#!/usr/bin/env python3
"""Propagate map/georef.yaml to everything that depends on it.

Writes:
  - map/base_map.yaml, map/keepout_draft.yaml   (origin <- origin_offset_m)
  - ros2_ws/src/my_bringup/config/gps_datum.yaml (datum for gps_to_map node)

Run from the repo root:  python3 map/tools/update_georef.py
"""
import os
import yaml

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

def main():
    with open(os.path.join(ROOT, 'map', 'georef.yaml')) as f:
        g = yaml.safe_load(f)
    ox, oy = g['origin_offset_m']

    for name in ('base_map', 'keepout_draft'):
        path = os.path.join(ROOT, 'map', f'{name}.yaml')
        with open(path, 'w') as f:
            f.write(f"""image: {name}.pgm
mode: trinary
resolution: {g['resolution']}
origin: [{float(ox)}, {float(oy)}, 0.0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25
""")
        print(f"wrote {path}")

    datum_path = os.path.join(ROOT, 'ros2_ws', 'src', 'my_bringup',
                              'config', 'gps_datum.yaml')
    os.makedirs(os.path.dirname(datum_path), exist_ok=True)
    with open(datum_path, 'w') as f:
        f.write(f"""# Generated by map/tools/update_georef.py — edit map/georef.yaml instead.
gps_to_map:
  ros__parameters:
    datum_lat: {g['datum']['lat']}
    datum_lon: {g['datum']['lon']}
    # map-frame position of the datum (matches the map yaml origin offset,
    # negated: a +east origin shift means the datum sits at -east in map frame)
    datum_x: {-float(ox)}
    datum_y: {-float(oy)}
""")
    print(f"wrote {datum_path}")

    lat, lon = g['datum']['lat'], g['datum']['lon']
    print(f"\nnavsat_transform datum (if you add robot_localization later): "
          f"[{lat}, {lon}, 0.0]")

if __name__ == '__main__':
    main()
