controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    ack_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
      
ack_cont:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: true  # Very important for hardware
    velocity_rolling_window_size: 10
    position_feedback: true
      # ADD THESE STEERING RATE LIMITS:
    # steering_angle_command:
    #   max_velocity: 1.0           # rad/s - max steering angular velocity
    #   max_acceleration: 2.0       # rad/s² - max steering acceleration
    
    rear_wheels_names: [left_rear_wheel_joint, right_rear_wheel_joint]
    front_wheels_names: [left_wheel_hinge, right_wheel_hinge]
    
    # CORRECTED VALUES FROM YOUR URDF:
    front_wheel_track: 0.52384      # 2 * 0.26192
    rear_wheel_track: 0.52384       # 2 * 0.26192  
    wheelbase: 0.36322              # front_wheel_offset_x
    
    front_wheels_radius: 0.0762     # wheel_radius from URDF
    rear_wheels_radius: 0.0762      # wheel_radius from URDF
    
    use_stamped_vel: true
    enable_odom_tf: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    odom_only_twist: false
    publish_rate: 50.0

    